Create AMG list-all-available-plugins
Azure/aaz pull request #547
Opened 2024-08-21 22:59 UTC by leozhang-msft

2024-08-27 21:33 UTC, ABZhang0 requested changes

2024-08-27 21:33 UTC, ABZhang0 commented on Commands/grafana/_list-available-plugin.md
> +list all the available plugins
Can we organize this command in a new 'az grafana plugins' subgroup? So something like 'az grafana plugins fetch' for this command

2024-09-09 08:02 UTC, ABZhang0 commented on Commands/grafana/_list-available-plugin.md
> +list all the available plugins
Never mind, this is already in effect, so don't want to create a breaking change at this point

2024-09-09 08:06 UTC, kairu-ms approved these changes

2024-09-09 08:07 UTC, merged